name: Build example

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=output/example.pdf
            example/input/example.md
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
