name: Build example

on: [push]

jobs:
  convert_via_pandoc:
    build:

      runs-on: ubuntu-18.04

      steps:
      - uses: actions/checkout@v2
      - run: mkdir example/output
      - uses: docker://pandoc/latex:2.9
        whth:
          args: |>
          --standalone
          --output=example/output/example.pdf
          example/input/example.md
